

server:
  port: 7000
  servlet:
    context-path: /api-user

spring:
  application:
    name: taoyiquan-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # 环境 dev|test|prod
  profiles:
    active: dev-mysql
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    #MySQL
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 962464
    url: jdbc:mysql://localhost:3306/xt_taoyiquan?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai




