
server:
  port: 8849

spring:
  application:
    name: taoyiquan-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: taoyiquan-admin
          uri: lb://taoyiquan-admin # lb: 使用负载均衡策略  默认应该是轮询策略
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: taoyiquan-user
          uri: lb://taoyiquan-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: taoyiquan-auth
          uri: lb://taoyiquan-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: taoyiquan-taobao
          uri: lb://taoyiquan-taobao
          predicates:
            - Path=/taobao/**
          filters:
            - StripPrefix=1

